# Generated by Django 6.0.3 on 2026-08-08 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='role',
            field=models.CharField(default='Agriculteur', max_length=20),
        ),
        migrations.CreateModel(
            name='BreakdownReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('checks_completed', models.TextField(default='{}')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_breakdowns', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('farm_name', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('last_connection', models.DateTimeField(auto_now=True)),
                ('wifi_signal', models.CharField(default='Bon', max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Disponible', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
